[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.78.2"
HUGO_THEME = "Cupper"
HUGO_BASEURL = "https://pugsandinfosec.com"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
